version: '3'
services:
  database:
    image: 'postgres'
    restart: 'always'
    ports:
      - 5632:5632
    env_file:
      - database.env
    networks:
      - webnet

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - webnet
    command: sh -c 'redis-server'

networks:
  webnet:
