version: '3'
services:
  database:
    image: 'postgres'
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - webnet

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - webnet
    command: sh -c 'redis-server'

networks:
  webnet:
